base:
  device: 1     # set to -1 if you don't have a GPU
  
data:
  dataset_folder: dataset
  images_folder: images
  all_qa_pairs_file: all_qa_pairs.txt
  train_dataset: data_train.csv
  eval_dataset: data_eval.csv
  question_col: question
  image_col: image_id
  answer_col: answer
  answer_space: answer_space.txt

tokenizer:
  padding: longest
  max_length: 24
  truncation: True
  return_token_type_ids: True
  return_attention_mask: True

model:
  name: roberta-beit  # Custom name for the multimodal model
  text_encoder: roberta-base # Valid transformer model for text encoding from HuggingFace
  image_encoder: microsoft/beit-base-patch16-224-pt22k-ft22k # Valid transformer model for image encoding from HuggingFace
  intermediate_dims: 512
  dropout: 0.5

trainer:
  default_root_dir: checkpoint
  max_epochs: 5
  log_every_n_steps: 100
  precision: 32    # set to 16 for mixed precision training

training:
  lr: 5.0e-5
  batch_size: 32
  num_workers: 8
  load_best_model_at_end: True
  num_sanity_val_steps: 0
  val_check_interval: 100

metrics:
  metrics_folder: metrics
  metrics_file: roberta-deit.json

inference:
  checkpoint: checkpoint-1500